### PR TITLE
Make main file compatible for bower and sass

### PR DESCRIPTION
**Pull request by mrlove**
see issue details on #52

### CODE REVIEW

**Comment by alwin-rewedigital** [comment]
Is this project dead already?

**Comment by JohnAlbin** [comment]
@alwin-rewedigital Nope. :-)

Let's keep the discussion in #52 since it has all the context.

**Comment by alwin-rewedigital** [comment]
could you please release a version of the current master?

**Comment by JohnAlbin** [comment]
@alwin-rewedigital done!

**Pull request merged**
