### PR TITLE
Improved box-model reset

### PR DESCRIPTION
**Pull request by garrettw**

### CODE REVIEW

**Comment by JohnAlbin** [comment]
@garrettw Looks great! I'll fix the failing tests.

**Comment by garrettw** [comment]
Oh, I just realized that I didn't put the ideal two colons on those pseudo-element selectors. However, if you want to maintain IE8 compatibility, I can just leave it as is.

**Comment by JohnAlbin** [comment]
I tried this new box-sizing inheritance method on my last project. And, unfortunately, I ran into a really hard-to-track down bug because of it.

If you use the `<details>` element on your page, Chrome will treat all of its children as having `box-sizing: content-box`.

https://caniuse.com/#search=details confirms this bug:

> In Chrome, when using the common inherit box-sizing fix (http://www.paulirish.com/2012/box-sizing-border-box-ftw/) in combination with a `<details>` element, the children of the `<details>` element get rendered as if they were box-sizing: content-box;. See: http://codepen.io/jochemnabuurs/pen/yYzYqM

When you experience this problem it is not at all obvious that the problem is due to the `<details>` element, either. I thought a CSS regression from my team was more likely than an obscure browser bug.

So my choice is to keep what we have; meaning devs will need to occasionally override for pre-built components that assume `content-box`. Or to switch to this new method; meaning devs will occasionally run into very hard-to-debug problems. :-\

**Comment by garrettw** [comment]
Would it not work to just add a specific fix for that issue?
```css
details * {
    box-sizing: border-box;
}
```
I just tested it in that codepen and it seemed to do the trick. That being said, from a performance perspective, I know that selector may not be optimal, so maybe there's some way to refine it but you get the gist.

**Comment by JohnAlbin** [comment]
```css
details * {
    box-sizing: border-box;
}
```

is equivalent (but with higher specificity) than

```css
* {
    box-sizing: border-box;
}
```

And has the same issue that our existing CSS has.

**Comment by JohnAlbin** [comment]
So, if we want the same `box-sizing: inherit;` property for children of `details`, we would need to modify the CSS to:


```
html,
details > * {
  box-sizing: border-box;
}

*, *:before, *:after,
details > * *,
details > * *:before,
details > * *:after {
  box-sizing: inherit;
}
```

vs. what we have now:

```
* {
  box-sizing: border-box;
}
```

**Comment by garrettw** [comment]
Well, I'm fine with whatever you think is best then.

**Comment by JohnAlbin** [comment]
6 years later and this browser bug is still unfixed. :-p

**Pull request closed without merging**
